build.gradle
src/main/java/popfri/spring/apiPayload/ApiResponse.java
src/main/java/popfri/spring/config/SwaggerConfig.java
src/main/java/popfri/spring/web/controller/TempRestController.java
src/main/java/popfri/spring/web/dto/TempResponse.java
src/main/resources/application.yml

- close #3           
- 스웨거 기초 설정
어떤 변경 사항이 있나요?
- 구현 화면입니다. (http://localhost:8080/swagger-ui/index.html#/)

[FEAT] #3 Swagger 설정

---

src/main/java/popfri/spring/OAuth2/dto/NaverResponse.java
src/main/java/popfri/spring/OAuth2/service/CustomOAuth2UserService.java
src/main/java/popfri/spring/config/SecurityConfig.java

- close #7             
- 네이버 로그인 구현
어떤 변경 사항이 있나요?
- 테스트 화면입니다. (http://localhost:8080/oauth2/authorization/naver)

[FEAT] #7 naver 로그인

---

src/main/java/popfri/spring/OAuth2/dto/KakaoResponse.java
src/main/java/popfri/spring/OAuth2/service/CustomOAuth2UserService.java
src/main/java/popfri/spring/domain/User.java
src/main/resources/application.yml

- close #9             
- 카카오 로그인 구현
어떤 변경 사항이 있나요?
- 테스트 화면입니다. (http://localhost:8080/oauth2/authorization/kakao)

[FEAT] #9 kakao 로그인

---

src/main/java/popfri/spring/OAuth2/handler/CustomSuccessHandler.java
src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
src/main/java/popfri/spring/config/SecurityConfig.java
src/main/java/popfri/spring/jwt/JWTFilter.java
src/main/java/popfri/spring/jwt/JWTUtil.java

- close #13          
- JWT 유효 기간 연장(60 * 60 * 60 -> 1000 * 60 * 60 * 5): 5시간
- spring security 접근 권한 변경(미로그인 스웨거 접속 가능)
어떤 변경 사항이 있나요?
- 결과 화면 입니다.

[FIX] #13 JWT 관련 오류 수정

---

src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
src/main/java/popfri/spring/domain/RecHistory.java
src/main/java/popfri/spring/domain/User.java
src/main/java/popfri/spring/domain/enums/RecType.java
src/main/java/popfri/spring/repository/RecHistoryRepository.java
src/main/java/popfri/spring/service/HistoryService.java
src/main/java/popfri/spring/service/MovieService.java
src/main/java/popfri/spring/web/controller/MovieController.java
src/main/java/popfri/spring/web/dto/GPTRequest.java
src/main/java/popfri/spring/web/dto/GPTResponse.java
src/main/java/popfri/spring/web/dto/MovieResponse.java

- close #18             
- 상황을 입력받아 gpt에게 영화 추천을 받은 뒤. TMDB api를 통해 추천 영화 출력
어떤 변경 사항이 있나요?
- 구현 화면입니다.

[FEAT] #18 상황별 영화 추천

---

src/main/java/popfri/spring/service/HistoryService.java
src/main/java/popfri/spring/service/MovieService.java
src/main/java/popfri/spring/web/controller/MovieController.java

- close #20            
- 현재 서버 시간을 gpt에게 전달한 뒤 tmdb로 추천 영화를 출력
어떤 변경 사항이 있나요?
- 구현 화면입니다.

[FEAT] #20 시간별 영화 추천

---

src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
src/main/java/popfri/spring/apiPayload/exception/handler/ReviewHandler.java
src/main/java/popfri/spring/domain/DislikeReview.java
src/main/java/popfri/spring/domain/LikeReview.java
src/main/java/popfri/spring/domain/Review.java
src/main/java/popfri/spring/domain/User.java
src/main/java/popfri/spring/repository/DislikeReviewRepository.java
src/main/java/popfri/spring/repository/LikeReviewRepository.java
src/main/java/popfri/spring/repository/ReviewRepository.java
src/main/java/popfri/spring/repository/UserRepository.java
src/main/java/popfri/spring/service/MovieService.java
src/main/java/popfri/spring/service/ReviewService.java
src/main/java/popfri/spring/service/UserService.java
src/main/java/popfri/spring/web/controller/ReviewController.java
src/main/java/popfri/spring/web/controller/UserController.java
src/main/java/popfri/spring/web/dto/MovieResponse.java
src/main/java/popfri/spring/web/dto/ReviewResponse.java
src/test/java/popfri/spring/service/ReviewServiceTest.java

- close #17 
- 리뷰 작성 기능 구현
- 리뷰 좋아요, 싫어요 기능 구현
- 리뷰 삭제 기능 구현
- 유저 리뷰 조회 기능 구현
- 영화별 리뷰 조회(좋아요순, 최신순) 기능 구현
어떤 변경 사항이 있나요?

[FEAT] #17 리뷰 작성 및 조회 기능

---

src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
src/main/java/popfri/spring/apiPayload/exception/handler/HistoryHandler.java
src/main/java/popfri/spring/converter/HistoryConverter.java
src/main/java/popfri/spring/repository/RecHistoryRepository.java
src/main/java/popfri/spring/service/HistoryService.java
src/main/java/popfri/spring/web/controller/UserController.java
src/main/java/popfri/spring/web/dto/HistoryResponse.java

- close #22              
- 유저가 추천 받았던 내역 조회
어떤 변경 사항이 있나요?
- 구현 화면입니다.

[FEAT] #22 유저 추천 기록 조회

---

src/main/java/popfri/spring/domain/VisitHistory.java
src/main/java/popfri/spring/repository/VisitHistoryRepository.java
src/main/java/popfri/spring/service/HistoryService.java
src/main/java/popfri/spring/web/controller/UserController.java
src/main/java/popfri/spring/web/dto/HistoryRequest.java

- close #27            
- 영화 정보와 쿠키 내 유저 정보를 입력 받아 유저 방문 기록에 저장
어떤 변경 사항이 있나요?
- 구현 화면입니다.

[FEAT] #27 유저 방문 기록 저장

---

build.gradle
src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
src/main/java/popfri/spring/service/MovieService.java
src/main/java/popfri/spring/service/ReviewService.java
src/main/java/popfri/spring/web/controller/MovieController.java
src/main/java/popfri/spring/web/dto/MovieResponse.java

- close #25           
- 영화 이름으로 TMDB API 호출 기능 구현
- 지정한 날짜의 박스오피스 순위 반환 기능 구현
어떤 변경 사항이 있나요?

[FEAT] #25 박스오피스 순위 반환 기능 구현

---

src/main/java/popfri/spring/converter/HistoryConverter.java
src/main/java/popfri/spring/repository/RecHistoryRepository.java
src/main/java/popfri/spring/repository/VisitHistoryRepository.java
src/main/java/popfri/spring/service/HistoryService.java
src/main/java/popfri/spring/web/controller/UserController.java

- close #30            
- 쿠키내 유저 정보를 통해 방문 기록 반환
어떤 변경 사항이 있나요?
- 구현 화면입니다.

[FEAT] #30 방문 기록 조회

---

src/main/java/popfri/spring/repository/ReviewRepository.java
src/main/java/popfri/spring/service/MovieService.java
src/main/java/popfri/spring/web/controller/MovieController.java
src/main/java/popfri/spring/web/dto/MovieResponse.java

- close #34            
- 영화 한줄평 추천 목록 조회
- 최근 한달 내 작성된 리뷰 중 연산 작업(좋아요 * 2 - 싫어요 * 1)을 통해 상위 10개 리뷰 반환
어떤 변경 사항이 있나요?
- 구현 화면입니다.

[FEAT] #34 영화한줄평 추천 기능 구현

---

src/main/java/popfri/spring/repository/RecHistoryRepository.java
src/main/java/popfri/spring/repository/VisitHistoryRepository.java
src/main/java/popfri/spring/service/HistoryService.java
src/main/java/popfri/spring/web/controller/UserController.java

- close #36            
-유저 활동 기록(추천 기록, 방문 기록) 삭제
어떤 변경 사항이 있나요?
- 구현 화면입니다.

[FEAT] #36 유저 활동 기록 삭제 구현

---

src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
src/main/java/popfri/spring/domain/User.java
src/main/java/popfri/spring/domain/enums/Gender.java
src/main/java/popfri/spring/service/UserService.java
src/main/java/popfri/spring/web/controller/UserController.java
src/main/java/popfri/spring/web/dto/UserRequest.java
src/main/resources/application.yml

- close #41            
어떤 변경 사항이 있나요?
- 구현 화면입니다.

[FEAT] #41 성별, 나이 입력

---

src/main/java/popfri/spring/service/MovieService.java
src/main/java/popfri/spring/web/controller/MovieController.java
src/main/java/popfri/spring/web/dto/MovieResponse.java

- close #24            
- 랜덤한 날짜의 박스오피스 영화 순위를 호출하여 영화 탐색 리스트 반환
어떤 변경 사항이 있나요?

[FEAT] #24 영화 탐색 리스트 조회 기능 구현

---

src/main/java/popfri/spring/OAuth2/handler/CustomSuccessHandler.java
src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
src/main/java/popfri/spring/apiPayload/exception/ExceptionAdvice.java
src/main/java/popfri/spring/apiPayload/exception/GeneralException.java
src/main/java/popfri/spring/config/CorsMvcConfig.java
src/main/java/popfri/spring/repository/DislikeReviewRepository.java
src/main/java/popfri/spring/repository/LikeReviewRepository.java
src/main/java/popfri/spring/repository/ReviewRepository.java
src/main/java/popfri/spring/service/MovieService.java
src/main/java/popfri/spring/service/ReviewService.java
src/main/java/popfri/spring/web/controller/MovieController.java
src/main/java/popfri/spring/web/controller/ReviewController.java
src/main/java/popfri/spring/web/dto/MovieResponse.java
src/main/java/popfri/spring/web/dto/ReviewResponse.java

- close #46  
- 리뷰 관련 error handler 설정 추가
- 리뷰 좋아요, 싫어요 로직 변경
- 리뷰 DTO 변수 이름 변경
- 리뷰 조회 페이지네이션 추가
- 리뷰 조회 시 유저 정보를 받아 리뷰마다 유저의 좋아요, 싫어요 여부 체크
어떤 변경 사항이 있나요?

[FEAT] #46 리뷰 로직 변경

---

src/main/java/popfri/spring/domain/User.java
src/main/java/popfri/spring/jwt/CookieUtil.java
src/main/java/popfri/spring/web/controller/UserController.java

- close #48             
- 로그아웃 기능 구현
- 회원탈퇴 오류 수정
어떤 변경 사항이 있나요?
- 구현 화면입니다.

[FEAT] #48 로그아웃 기능 구현

---

src/main/java/popfri/spring/OAuth2/handler/CustomSuccessHandler.java
src/main/java/popfri/spring/converter/UserConverter.java
src/main/java/popfri/spring/web/controller/UserController.java
src/main/java/popfri/spring/web/dto/UserResponse.java

- close #50          
- 유저 정보 조회 시 성별, 나이 조회 추가.
어떤 변경 사항이 있나요?

[FEAT] #50 유저 성별, 나이 조회 구현

---

dockerfile
src/main/java/popfri/spring/web/controller/UserController.java

- close #52          
- user provide_id 반환 컨트롤러 작성
어떤 변경 사항이 있나요?

[FEAT] #52 유저 provide_id 반환 컨트롤러 작성

---

src/main/java/popfri/spring/config/SecurityConfig.java
src/main/java/popfri/spring/jwt/JWTFilter.java
src/main/java/popfri/spring/repository/VisitHistoryRepository.java
src/main/java/popfri/spring/service/HistoryService.java
src/main/java/popfri/spring/sse/SseController.java
src/main/java/popfri/spring/sse/SseEmitters.java
src/main/java/popfri/spring/web/dto/HistoryResponse.java

- close #54           
- 성별, 나이별 선호 영화 실시간 반환
- 선호 영화 월간, 주간 데이터 반환
어떤 변경 사항이 있나요?

[FEAT] #53 성별, 나이 별 선호영화 데이터 반환

---

src/main/java/popfri/spring/repository/RecHistoryRepository.java
src/main/java/popfri/spring/service/HistoryService.java
src/main/java/popfri/spring/sse/SseController.java
src/main/java/popfri/spring/sse/SseEmitters.java

- close #56          
- 추천 영화 반환, 방문 영화 반환, 메서드 중복 코드 처리
- 성별, 나이 별 추천 영화 데이터 기간 별 반환 메서드 구현
- 기록 유형 별 리스너 설정 
어떤 변경 사항이 있나요?

[FEAT] #56 성별, 나이 별 추천 영화 데이터 반환

---

src/main/java/popfri/spring/repository/VisitHistoryRepository.java
src/main/java/popfri/spring/service/MovieService.java
src/main/java/popfri/spring/sse/SseController.java
src/main/java/popfri/spring/sse/SseEmitters.java
src/main/resources/application.yml

- close #61         
- 성별, 나이 통합 방문 데이터 메서드 추가
- tmdb 추천영화 로드 시 방어로직 추가
어떤 변경 사항이 있나요?

[FEAT] #61 성별, 나이 통합 방문 데이터 반환
